services:
    watershine_firebase.cloud_messaging:
        class: Watershine\FirebaseBundle\Service\CloudMessagingImpl

    Watershine\FirebaseBundle\Service\CloudMessagingInterface: '@watershine_firebase.cloud_messaging'
